#
# Makefile -- Baue das Beispiel-Programm zum Regex-Matcher der C-Library
#
# (c) 2010 Prof Dr Andreas Mueller, Hochschule Rapperswil
#
regex:	regex.c
	gcc -Wall -O -g -o regex regex.c

test:	regex
	./regex
