#
# Makefile
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
images:	zahlen.pdf zahlen0.pdf zahlennea.pdf teilbarkeit.pdf

zahlen.pdf:	zahlen.tex
	pdflatex zahlen.tex

zahlen0.pdf:	zahlen0.tex
	pdflatex zahlen0.tex

zahlennea.pdf:	zahlennea.tex
	pdflatex zahlennea.tex

teilbarkeit.pdf:	teilbarkeit.tex
	pdflatex teilbarkeit.tex

