#
# Makefile
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
#biber.jpg:	DSC_0559.jpg
#	convert DSC_0559.jpg -scale 50% \
#		-density 300 -units PixelsPerInch biber.jpg

biber2.jpg:	biber.jpg
	convert biber.jpg -scale 50% \
		-density 300 -units PixelsPerInch biber2.jpg
