#
# Makefile -- build 
#
# (c) 2019 Prof Dr Andreas Müller, Hochschule Rapperswil
#
all:	graph.pdf graph-loesung.pdf

graph.pdf:	graph.tex graph-common.tex
	pdflatex graph.tex

graph-loesung.pdf:	graph-loesung.tex graph-common.tex
	pdflatex graph-loesung.tex


