#
# Makefile -- build images for cfg chapter
#
# (c) 2019 Prof Dr Andreas Müller, Hochschule Rapperswil
#
all:	pda-stacknichtleer.pdf pda-stackleer.pdf

pda-stacknichtleer.pdf:	pda-stacknichtleer.tex stacknichtleer.tex
	pdflatex pda-stacknichtleer.tex

pda-stackleer.pdf:	pda-stackleer.tex stackleer.tex
	pdflatex pda-stackleer.tex

